I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 18, in script call
    call variables
  File "game/script.rpy", line 18, in script call
    call variables
ScriptError: could not find label 'variables'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 18, in script call
    call variables
  File "renpy/ast.py", line 1485, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 18, in script call
    call variables
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'variables'.

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
genshiken 1.0
Mon Oct 18 15:51:27 2021
